# Generated by Django 5.1.2 on 2024-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='blob_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
