# Generated by Django 5.1.2 on 2024-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0003_alter_customimage_blob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendition',
            name='rendition_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
