# Generated by Django 5.1.2 on 2024-11-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0004_customrendition_rendition_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendition',
            name='rendition_url',
        ),
    ]
