# Generated by Django 5.1.2 on 2024-12-11 16:35

import custom_user.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailusers', '0015_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailusers.userprofile')),
                ('custom_avatar', models.ImageField(blank=True, max_length=255, upload_to=custom_user.models.upload_avatar_to, verbose_name='profile picture')),
            ],
            bases=('wagtailusers.userprofile',),
        ),
    ]
