# Generated by Django 5.1.2 on 2024-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
