# Generated by Django 5.1.2 on 2024-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebear_cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='safebear_cms',
        ),
        migrations.AddField(
            model_name='locationpage',
            name='website',
            field=models.TextField(blank=True, verbose_name='Website'),
        ),
    ]
